const Router = require('express')
const router = new Router()
const authRouter = require('./AuthRouter')
const cartRouter = require('./CartRouter')
const favRouter = require('./FavRouter')
const itemRouter = require('./ItemRouter')
const orderRouter = require('./OrderRouter')
const orderItemRouter = require('./OrderItemRouter')
const orderPhotoRouter = require('./OrderPhotoRouter')
const promoRouter = require('./PromoRouter')
const photoRouter = require('./PhotoRouter')
const sizeRouter = require('./SizeRouter')
const storyRouter = require('./StoryRouter')
const userRouter = require('./UserRouter')
const cdekRouter = require('./CdekRouter')
const constantsRouter = require('./ConstantsRouter')

router.use('/auth', authRouter)
router.use('/cart', cartRouter)
router.use('/fav', favRouter)
router.use('/item', itemRouter)
router.use('/order', orderRouter)
router.use('/order_item', orderItemRouter)
router.use('/order_photo', orderPhotoRouter)
router.use('/promo', promoRouter)
router.use('/photo', photoRouter)
router.use('/size', sizeRouter)
router.use('/story', storyRouter)
router.use('/user', userRouter)
router.use('/cdek', cdekRouter)
router.use('/constants', constantsRouter)

module.exports = router